#!/bin/bash

script_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
tokens=(${1//\./ })
class_name=${tokens[${#tokens[@]} - 1]}
unset tokens[${#tokens[@]}-1]
package_name=$(printf ".%s" "${tokens[@]}")
package_name=${package_name:1}
package_dir=$(printf "/%s" "${tokens[@]}")
package_dir=${package_dir:1}
mkdir -p "$package_dir"
cp $script_dir/assets/init-java/class.java `pwd`/$package_dir/$class_name.java
sed -i "" "1s/__package__/$package_name/" `pwd`/$package_dir/$class_name.java
sed -i "" "3s/__name__/$class_name/" `pwd`/$package_dir/$class_name.java